name: Soft Activity

on:
  schedule:
    - cron: "53 18 * * *" 
  workflow_dispatch:

# ADD THIS SECTION HERE
permissions:
  contents: write

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: Small heartbeat
        run: |
          echo "$(date +'%Y-%m-%d')" >> activity.log

      - name: Commit softly
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add activity.log
          git commit -m "chore: minor activity" || exit 0
          git push
